version: "3"
services:
  scstore-app:
    image: scstore:1.0.0
    environment:
      - DB_HOSTNAME=10.107.128.2
      - DB_PORT=5432
      - DB_USERNAME=scstore
      - DB_PASSWORD=scstore
      - DB_NAME=scstore
      - GIN_MODE=release
    ports:
      - "80:8080"